notifications:
  email:
    on_success: never
    on_failure: never
env:
  global:
  - PORT=55333
  - DEPLOY_DIR=/home/Docker/natgeo/
addons:
  ssh_known_hosts: "$IP:$PORT"
before_install:
- openssl aes-256-cbc -K $encrypted_59648f6afd5a_key -iv $encrypted_59648f6afd5a_iv
  -in id_rsa.enc -out ./id_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 ./id_rsa
- echo -e "Host $IP\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./id_rsa
- ssh -p $PORT -i ./id_rsa $USER@$IP pwd
deploy:
- provider: script
  skip_cleanup: true
  script: "bash .travis/deploy.sh"
  on:
    branch: master
