version: '3'
services:
  bot6:
    build: ./6bot_geo
    restart: always
    volumes:
      - ./6bot_geo:/code
    env_file:
      - .env
  
  bot5:
    build: ./5bot_geo
    restart: always
    volumes:
      - ./5bot_geo:/code

  bot4:
    build: ./4bot_geo
    restart: always
    volumes:
      - ./4bot_geo:/code

  bot3:
    build: ./3bot_geo
    restart: always
    volumes:
      - ./3bot_geo:/code

  bot2:
    build: ./2bot_geo
    restart: always
    volumes:
      - ./2bot_geo:/code

  bot1:
    build: ./1bot_geo
    restart: always
    volumes:
      - ./1bot_geo:/code
    env_file:
      - .env

  insta:
    build: ./insta
    restart: always
    volumes:
      - ./insta:/code

